/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectQueue;

import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunisa Liangtrakool
 */
public class FormSummary extends javax.swing.JFrame {

    ServiceManageDriver serviced;

    /**
     * Creates new form FormSummary
     */
    public FormSummary() {
        initComponents();
        Database.Database();
        serviced = new ServiceManageDriver();
        showSummary();
    }

    public void showSummary() {
        List<Drivers> driverList = serviced.findAllDriver();
        Iterator<Drivers> cursor = driverList.iterator();

        String[] column = {"FirstName", "Number", "Count", "Income"};

        DefaultTableModel model = new DefaultTableModel(column, 0);

        try {
            while (cursor.hasNext()) {
                Drivers driver = cursor.next();
                String FirstName = driver.getDriverFirName();
                String Number = driver.getDriverNumber();
                String Count = driver.getDriverCount();
                String Income = driver.getDriverIncome();

                model.addRow(new Object[]{FirstName, Number, Count, Income});
            }
        } finally {

        }
        tableShowIncome.setModel(model);
    }

    public void search(String searchNumber) {
        try {
            Drivers cursor = serviced.findDriverByNumber(searchNumber);

            String[] column = {"FirstName", "Number", "Count", "Income"};

            DefaultTableModel model = new DefaultTableModel(column, 0);
            Drivers driver = cursor;
            String FirstName = driver.getDriverFirName();
            String Number = driver.getDriverNumber();
            String Count = driver.getDriverCount();
            String Income = driver.getDriverIncome();
            model.addRow(new Object[]{FirstName, Number, Count, Income});

            tableShowIncome.setModel(model);
        } catch (Exception e) {
            alertMessage("ไม่มีเบอร์หลังเสื้อนี้อยู่ในระบบ");
            txtSearchNumber.setText("");
        }

    }

    public void alertMessage(String message) {
        JLabel label = new JLabel(message);
        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowIncome = new javax.swing.JTable();
        labelNumber = new javax.swing.JLabel();
        txtSearchNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuDriver = new javax.swing.JMenu();
        menuPassenger = new javax.swing.JMenu();
        menuLocation = new javax.swing.JMenu();
        menuQueue = new javax.swing.JMenu();
        menuSummary = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(785, 580));

        tableShowIncome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableShowIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableShowIncome);

        labelNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNumber.setText("Number");

        txtSearchNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(153, 153, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnShowAll.setBackground(new java.awt.Color(153, 153, 255));
        btnShowAll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        menuHome.setText("หน้าแรก");
        menuHome.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuHome);

        menuDriver.setText("จัดการผู้ขับขี่");
        menuDriver.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        menuDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDriverMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuDriver);

        menuPassenger.setText("จัดการลูกค้า");
        menuPassenger.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        menuPassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPassengerMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuPassenger);

        menuLocation.setText("จัดการสถานที่");
        menuLocation.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        menuLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLocationMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuLocation);

        menuQueue.setText("จัดการคิว");
        menuQueue.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        menuQueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQueueMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuQueue);

        menuSummary.setText("สรุปรายได้");
        menuSummary.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        menuSummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSummaryMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuSummary);

        menuLogout.setText("ออกจากระบบ");
        menuLogout.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuLogout);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(labelNumber)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumber)
                    .addComponent(txtSearchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowAll)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:
        new FormHome().show();
        this.dispose();
    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDriverMouseClicked
        // TODO add your handling code here:
        new FormManageDriver().show();
        this.dispose();
    }//GEN-LAST:event_menuDriverMouseClicked

    private void menuPassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPassengerMouseClicked
        // TODO add your handling code here:
        new FormManagePassenger().show();
        this.dispose();
    }//GEN-LAST:event_menuPassengerMouseClicked

    private void menuQueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQueueMouseClicked
        // TODO add your handling code here:
        new FormManageQueue().show();
        this.hide();
    }//GEN-LAST:event_menuQueueMouseClicked

    private void menuSummaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSummaryMouseClicked
        // TODO add your handling code here:
        this.show();
    }//GEN-LAST:event_menuSummaryMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        showSummary();
        txtSearchNumber.setText("");
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (txtSearchNumber.getText().equals("")) {
            alertMessage("กรุณากรอกข้อมูล");

        } else {
            search(txtSearchNumber.getText());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void menuLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLocationMouseClicked
        // TODO add your handling code here:
        new FormManageLocation().show();
        this.dispose();
    }//GEN-LAST:event_menuLocationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNumber;
    private javax.swing.JMenu menuDriver;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenu menuLocation;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuPassenger;
    private javax.swing.JMenu menuQueue;
    private javax.swing.JMenu menuSummary;
    private javax.swing.JTable tableShowIncome;
    private javax.swing.JTextField txtSearchNumber;
    // End of variables declaration//GEN-END:variables
}
